name: language
description: A new Flutter project.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/numbers/
    - assets/images/colors/
    - assets/images/family_members/
    - assets/sounds/colors/
    - assets/sounds/family_members/
    - assets/sounds/numbers/
    - assets/sounds/phrases/



